### ISSUE TITLE
Double print message to Rocket.log

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Legally-Distinct-Missile#28] opened 2020-08-02 03:42 UTC
API `Rocket.Core.Logging.Logger.Log(string message)` will print message twice to the log file. Is that Bug or ?

##  Rocket.log

[2020/8/2 10:05:50] [Info] PVP >> Init..
[2020/8/2 10:05:50] [Info] PVP >> Init..
[2020/8/2 10:06:44] [Info] PVP >> PostLevelLoaded: 2
[2020/8/2 10:06:44] [Info] PVP >> PostLevelLoaded: 2

**Comment by Trojaner** [comment] 2020-08-02 11:16
I can confirm this

**Comment by SDGNelson** [comment] 2020-08-02 14:58
Off the top of my head it might be writing to the log file, and then getting logged again once it goes through the Unturned console. Ideally newer could should use the built-in CommandWindow or UnturnedLog functions - Rocket is routed through those, and all of the base game logging uses them.

**Comment by joeymisfit** [comment] 2020-08-07 01:51
@SDGNelson I can also confirm this issue, I work in customer service for a game server host and it's a constant issue. Might I also add the printed messages start when the command /Extras starts loading. Is there a way to possibly fix the duplication glitch?

**Comment by SDGNelson** [comment] 2020-08-07 16:39
Alright, since several people have asked about it I will see about sorting it out for the next update.

**Comment by joeymisfit** [comment] 2020-08-10 21:57
@SDGNelson Was the update supposed to be apart of this mornings update?

**Comment by SDGNelson** [comment] 2020-08-10 23:44
Nope - the update this morning was to address issues with signs that spread wildly on Sunday. Here are more details: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1933#issuecomment-671163285

**Comment by SDGNelson** [comment] 2020-09-01 22:16
This should be fixed in the next update. Here is the commit that fixes it: https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/commit/126a827507d7037f9bb7aaa7371a4ff3748839d2

**Closed** 2020-09-24 00:25 UTC

**Comment by joeymisfit** [comment] 2020-09-24 00:35
Thank you for fixing this, it's been such a pain with the double print.
