### ISSUE TITLE
IO buffer bug

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Legally-Distinct-Missile#21] opened 2020-06-15 00:41 UTC
Bug found with rocket console
[Video](https://streamable.com/v723wo)
This bug happen in a fresh server with just rocketmod
Unturned server command: `start /SEPARATE Unturned.exe -nographics -batchmode -silent-crashes +secureserver/Test_Rm4`

**Comment by SDGNelson** [comment] 2020-06-15 18:47
I double-checked with and without Rocket and it worked properly for me.

Are you using the SDG-maintained version/a fork of it? If not, it will become mandatory in the next update. Can you share why not?

The console functions block the calling thread which is why the game's built-in console runs them from a separate thread.

**Comment by rube200** [comment] 2020-06-15 18:58
I was using a fresh version of server.
(i reinstalled both client/server files two days before this report)

`@echo off
cd "C:\Program Files (x86)\Steam\steamapps\common\Unturned_Server"
move /Y Modules\Rocket5 Rocket5 >nul 2>&1
move /Y Rocket4 Modules\Rocket4 >nul 2>&1
echo -SkipAssets
start /SEPARATE Unturned.exe -nographics -batchmode -silent-crashes +secureserver/Test_Rm4`

**Comment by SDGNelson** [comment] 2020-06-15 19:24
Are you using the SDG-maintained version of Rocket though? Either from the Extras directory, this repository, or a fork of this repository.

**Comment by rube200** [comment] 2020-06-15 19:43
Copy-paste from extras folder

**Comment by SDGNelson** [comment] 2020-06-15 23:37
Does it happen if you run the ExampleServer.bat script?

Also based on "with just rocketmod" I assume you have no plugins for this test, but just in case, do you have any plugins?

**Comment by rube200** [comment] 2020-06-16 12:44
I had tested it with my plugin ORP on the  server but I knew it wouldn't affect it.
Now I ran the script you said (I had to move the server to C: because of the path) and now with 0 changes (plugins / config ...) the bug continues to happen, but a funny thing happened when I put a id/name that is invalid it returns the correct message from the server, so it's probably related to `Rocket.Core.Logger.Log`


This error also appeared btw:
`An error occured while executing v [12323]: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.Commands.CommandV.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x000f9] in <59f13c7b8fd2452db84433be578fe6c9>:0
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <466fa14d466749559a64a11ae8acbc60>:0
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x001b2] in <466fa14d466749559a64a11ae8acbc60>:0
[World] Spirits [ⓇⓊⒷⒺ②🄋🄋]: "/v 12323"`
(not output in chat for it, and /i 12323 returns the correct msg)

**Comment by SDGNelson** [comment] 2020-06-16 15:28
Why did you have to move it to the C drive? Nothing in the game or those scripts should rely on a specific drive letter. For my tests it was on the D drive.

Is it possible that your ORP plugin uses the Console class somewhere? e.g. Console.WriteLine

I think you may be right that something in Rocket.Core uses the Console class, will check into that.

**Comment by XanderCodes** [comment] 2020-06-23 05:05
I may have completely misread the thread, but looking at the video, I believe this is caused by Windows' terminal, mainly the QuickEdit function... see [this](https://stackoverflow.com/questions/591047/command-line-windows-hanging-in-rdp-windows) and [this](https://stackoverflow.com/questions/30418886/how-and-why-does-quickedit-mode-in-command-prompt-freeze-applications) from StackOverflow. 

All you have to do to fix it is right-click on the console's title bar, click Properties, then disable "QuickEdit Mode"

**Comment by SDGNelson** [comment] 2020-06-23 15:29
I think the reason I didn't run into the same freeze was that I used the built-in vehicle/give commands rather than the Rocket alternatives. Checking the Rocket.Core code a couple days ago it does directly use the Console functions, so in the next update it will be routed through Unturned instead.

**Comment by SDGNelson** [comment] 2020-07-02 20:53
This should be fixed in the next update. Thanks for the report @rube200! All usage of `System.Console` has been replaced with `SDG.Unturned.CommandWindow`.

**Closed by SDGNelson** 2020-07-02 20:53 UTC
